global using ClientCompanies = System.Collections.Generic.IEnumerable<Shared.DTOs.Responses.ToClientCompany>;
global using ClientEmployees = System.Collections.Generic.IEnumerable<Shared.DTOs.Responses.ToClientEmployee>;
global using Microsoft.AspNetCore.Mvc;
global using Service.Contracts;
global using Shared.DTOs.Responses;
global using Shared.DTOs.Requests;
global using Microsoft.AspNetCore.Mvc.ModelBinding;
global using System.ComponentModel;
global using System.Reflection;
global using Presentation.ModelBinders;
global using Shared.DTOs;
global using Microsoft.AspNetCore.JsonPatch;
global using Shared.ParameterObjects;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Presentation.ActionFilters;
global using Shared.RequestFeatures;
global using System.Text.Json;
global using System.Dynamic;
global using Entities.LinkModels;
global using Microsoft.AspNetCore.Routing;